name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Python flake8 Lint
      uses: py-actions/flake8@v1.1.0
      with:
        path: .
    - name: Run Python scripts
      run: for d in ./*/ ; do (cd "$d" && python day*.py); done
